In [5]:
import torch
import torch.nn as nn
from torch.nn import functional as F

定义一个线性模型，输入维度是in_dim,输出维度是out_dim

In [13]:
class Linear_model(nn.Module):
    def __init__(self,in_dim,out_dim):
        super(Linear_model,self).__init__()
        self.input = nn.Linear(in_dim,out_dim)
    def forward(self,x):
        out = self.input(x)
        return out

In [15]:
x = torch.randn(3,32)
model = Linear_model(32,2)
out = model(x)
out.shape,out

(torch.Size([3, 2]),
 tensor([[-1.0088, -0.6627],
         [-0.9053, -0.4485],
         [ 0.3277,  0.0803]], grad_fn=<AddmmBackward0>))

使用sigmoid激活函数，公式:
$$f(x) = \frac{1}{1 + e^{-z}}$$ \
使用torch.sigmoid是对tensor中每个数应用这个公式

In [22]:
activation_sigmoid = torch.sigmoid(out)
activation_sigmoid.shape,activation_sigmoid

(torch.Size([3, 2]),
 tensor([[0.2672, 0.3401],
         [0.2880, 0.3897],
         [0.5812, 0.5201]], grad_fn=<SigmoidBackward0>))

使用softmax函数，公式：
$$ f(x) = \frac{e^{i}}{e^1 + e^2 +....+ e^n}$$
其中使用torch.softmax时需要指定维度，在二维数据中，如果指定dim=0，那么意思是逐行计算，则每一列的数据都会归一化，求和为1，如果dim=1，那么意思是逐列计算，则每一行的数据都会归一化，求和为1
在本例中，我们随机生成的数据维度是3*32，则说明有3个样本，每个样本特征维度为32，模型的输出是2维的，说明模型可能在做一个二分类的问题，则我们在此时使用softmax函数应该逐列计算，指定维度为dim=1，这样每一行两个数据，每一个数据表示属于某个类别的概率

In [26]:
activation_softmax = torch.softmax(out,dim=1)
activation_softmax.shape,activation_softmax

(torch.Size([3, 2]),
 tensor([[0.4143, 0.5857],
         [0.3877, 0.6123],
         [0.5615, 0.4385]], grad_fn=<SoftmaxBackward0>))

relu激活函数,公式：
$$ f(x) = max(0,x) $$

In [29]:
activation_relu = torch.relu(out)
activation_relu.shape,activation_relu

(torch.Size([3, 2]),
 tensor([[0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.3277, 0.0803]], grad_fn=<ReluBackward0>))

自定义一个神经网络模型，他包含两个线性层

In [44]:
class MLP(nn.Module):
    def __init__(self,in_dim,hidden_dim,out_dim):
        super(MLP,self).__init__()
        
        self.linear1 = nn.Linear(in_dim,hidden_dim)
        self.linear2 = nn.Linear(hidden_dim,out_dim)
    
    def forward(self,x):
        
        out1 = self.linear1(x)
        
        out1 = torch.relu(out1)
        
        out2 = self.linear2(out1)
        
        prob = torch.softmax(out2,dim=1)
        return prob

In [45]:
x = torch.randn(3,4)
model_mlp = MLP(4,5,2)
out = model_mlp(x)
out.shape,out

(torch.Size([3, 2]),
 tensor([[0.4154, 0.5846],
         [0.5167, 0.4833],
         [0.4205, 0.5795]], grad_fn=<SoftmaxBackward0>))